module.exports=[
    {
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    },{
        name:'Adele-Rolling-in-the-Deep',
        path:'D:/github/electron-player/video/Adele-Rolling-in-the-Deep.mp4',
        title:'Adele-Rolling-in-the-Deep'
    },{
        name:'frag_bunny',
        path:'D:/github/electron-player/video/frag_bunny.mp4',
        title:'frag_bunny'
    }
    
]